AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'my-sls-app

  Sample SAM Template for my-sls-app

  '
Globals:
  Function:
    Timeout: 60
Resources:
  GetEC2RegionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetEC2Regions
      Description: SAM Demo Get EC2 Regions
      Role: arn:aws:iam::320562446226:role/AdministratorAccessRole
      CodeUri: s3://pdomala-sam-demo/15495e61be6032300604047ae2fe2e61
      Handler: main.lambda_handler
      Runtime: python3.7
      Events:
        GetEC2RegionsAPI:
          Type: Api
          Properties:
            Path: /getec2regions
            Method: get
Outputs:
  GetEC2RegionsApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Production/getec2regions/
  GetEC2RegionsFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetEC2RegionsFunction
      - Arn
